In [9]:
import numpy as np
print("Hello")
print(np.__version__)

Hello
2.4.4


In [17]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [18]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [19]:
c=np.zeros([2,3])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
d=np.ones([3,2])
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
f=np.arange(0,10,2)
print(f)

[0 2 4 6 8]


In [22]:
g=np.linspace(0,10,3)
print(g)

[ 0.  5. 10.]


In [23]:
h=np.eye(4)
print(h)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
i=np.random.rand(2,3)
print(i)

[[0.26758233 0.73111981 0.70186449]
 [0.21663468 0.61300219 0.93820823]]


In [26]:
print(np.zeros([2,3]))
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# Exercise
a=np.arange(0,21,4)
b=np.linspace(0,20,6)
print(a,b)

[ 0  4  8 12 16 20] [ 0.  4.  8. 12. 16. 20.]


In [28]:
a=np.ones((4,4)) *7
print(a)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]
 [7. 7. 7. 7.]]
