In [2]:
import numpy as np

In [3]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[0])
print(a[3])
print(a[-1])

10
40
80


In [4]:
print(a[0:5:2])
print(a[::2])
print(a[::-1])

[10 30 50]
[10 30 50 70]
[80 70 60 50 40 30 20 10]


In [5]:
b=[[1,2,3],
   [4,5,6],
   [7,8,9]]
b=np.array(b)
print(b[0,0])
print(b[1,2])
print(b[2,-1])


1
6
9


In [8]:
print(b[0,])
print(b[:,2])
print(b[0:2,0:2])
print("----")
print(b[:,1:])


[1 2 3]
[3 6 9]
[[1 2]
 [4 5]]
----
[[2 3]
 [5 6]
 [8 9]]


In [14]:
# Exercise
a=np.array([5, 10, 15, 20, 25, 30, 35, 40])
print(a[-3:])
print(a[1::3])
print(a[::-1])

[30 35 40]
[10 25 40]
[40 35 30 25 20 15 10  5]


In [20]:
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(m[2,:])
print(m[:,1])
print(m[2:,2:])

[ 9 10 11 12]
[ 2  6 10 14]
[[11 12]
 [15 16]]
