In [36]:
import numpy as np

In [37]:
a= np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
c=a.reshape(6,2)
print(c)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [40]:
d= b.flatten()
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
e=b.ravel()
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
d[0]=999
print(d)
print(b)

[999   2   3   4   5   6   7   8   9  10  11  12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
e[0]=134
print(e)
print(b)

[134   2   3   4   5   6   7   8   9  10  11  12]
[[134   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [45]:
print(np.transpose(a))

[134   2   3   4   5   6   7   8   9  10  11  12]


In [ ]:
# Exercises 
a=np.arange(1,25)
b=a.reshape(8,3)

