In [10]:
import numpy as np

a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])

print(a+b)
print(a*b)
print("-----")
print(np.dot(a,b))
print(np.matmul(a,b))
print(a@b)

inverse = np.linalg.inv(a)
print(inverse)
print(np.linalg.det(a))


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
-----
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [ ]:
# Exercise
x = np.array([[2, 0], 
              [1, 3]])
y = np.array([[1, 1], 
              [0, 2],])
print(x*y)
print(x@y)

print(np.linalg.det(a))


[[2 0]
 [0 6]]
[[2 2]
 [1 7]]
