In [6]:
import numpy as np

a = np.array([1, 4, 9, 16])
b = np.array([-3, -1, 2, 5])

print(np.sqrt(a))
print(np.exp(b))
print(np.log(a))
print(np.abs(b))


[1. 2. 3. 4.]
[4.97870684e-02 3.67879441e-01 7.38905610e+00 1.48413159e+02]
[0.         1.38629436 2.19722458 2.77258872]
[3 1 2 5]


In [12]:
scores=np.array([70,95,60,88,75])
print(np.sort(scores))

print(np.argsort(scores))
print(np.where(scores>80))
print(np.argmax(scores))
print(np.argmin(scores))


[60 70 75 88 95]
[2 0 4 3 1]
(array([1, 3]),)
1
2
