In [ ]:
import numpy as np
print(np.random.rand(3))

#np.random.seed(41)
print(np.random.rand(3))

[0.59165399 0.7682703  0.90985679]
3


In [58]:
print(np.random.randint(1,10,size=2))

[6 3]


In [59]:
print(np.random.randn(5))

[-0.80365083 -0.89093471 -0.40589936 -2.34342591 -0.65513745]


In [60]:
print(type(np.nan))

<class 'float'>


In [71]:
data= np.array([10,20,np.nan,40,np.nan])
print(data==np.nan)

#Finding NaN values
print(np.isnan(data))

print(np.sum(data))
print(np.nansum(data))
print(np.nanmean(data))
data2=np.where(np.isnan(data),0,data)
print(data2)



[False False False False False]
[False False  True False  True]
nan
70.0
23.333333333333332
[10. 20.  0. 40.  0.]
