In [9]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
print(a[[0,2,3,5]])
print(a[[3,3,0]])

b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(b[[0,2]])

print(b[[0,1,2],[0,1,0]])
print(b[[0,2],[1,0]])




[10 30 40 60]
[40 40 10]
[[1 2]
 [5 6]]
[1 4 5]
[2 5]


In [14]:
#Exercise
a = np.array([100, 200, 300, 400, 500])
print(a[[4,0,2]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[[1,2]])
print(b[[0,1,2],[2,1,0]])



[500 100 300]
[[4 5 6]
 [7 8 9]]
[3 5 7]


In [9]:
# Stacking
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

print(np.vstack((a,b)))
print("-----------")
print(np.hstack((a,b)))

c = np.array([[1, 2], 
              [3, 4]])

d = np.array([[5, 6], 
              [7, 8]])

print(np.concatenate((c,d),axis=0))
print(np.concatenate((c,d),axis=1))

e=np.array([1,2,3,4,5,6])
f=np.split(e,3)
print(f[0])


[[1 2 3]
 [4 5 6]]
-----------
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[1 2]


In [14]:
#Ex
x=np.array([1,2])
y=np.array([3,4])
print(np.hstack((x,y)))
print(np.vstack((x,y)))

m=np.array([[1,2],
            [3,4]])
n=np.array([[5,6],
            [7,8]])

print(np.concatenate((m,n),axis=1))
z = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(np.split(z,4))

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 2 5 6]
 [3 4 7 8]]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]
